### ISSUE TITLE
Un-install tutorial?

### ISSUE THREAD

**Issue by iscrit** [Nookure/NookTheme#10]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I need to delete nook theme so i can use blueprint addons.

### Describe the solution you'd like.

I need to delete nook theme so i can use blueprint addons!!!

**Comment by iscrit** [comment]
Would be nice if someone could get me a 1 line command of rm -rf to delete all nook files.

**Comment by ralemac7** [comment]
To uninstall NookTheme you have to follow the steps on the Pterodactyl Panel documentation for Updating the panel. This will not remove any data or servers
https://pterodactyl.io/panel/1.0/updating.html
