### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by FRFlo** [Nookure/NookTheme#4]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Can you trigger the docker image build workflow and so, publish the docker image on the free ghcr registry ?

### Describe the solution you'd like.

Trigger the workflow, patch all bugs and then publish the image

**Comment by Lunna5** [comment]
Check the package ghcr.io/nookure/nooktheme

**Comment by FRFlo** [comment]
The package is unavailable, check if it's in public
