### ISSUE TITLE
The panel is white

### ISSUE THREAD

**Issue by ezz3r** [Nookure/NookTheme#8]
### Current Behavior

I installed it and now i see only an whole white color image.

### Expected Behavior

Show me a nice design for panel.

### Steps to Reproduce

I just installed it normaly.

### Panel Version

1.4.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Lunna5** [comment]
Could you provide the panel or web console logs ?
